platform :ios, "7.1"

pod 'AFNetworking'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.12'
pod 'googleplus-ios-sdk', '~> 1.7.1'
pod 'Parse'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'SDWebImage'
pod 'FBLikeLayout'
pod 'MarqueeLabel'
pod 'CHTCollectionViewWaterfallLayout'

target :AsyncImageListTests, :exclusive => true do
  # pod 'Kiwi'
end